import { DetectedFieldType } from '../../types'

/**
 * Universal Field Taxonomy & Synonym Mappings (Phase 2C)
 * Deterministic matching rules — no AI.
 */

export interface FieldDefinition {
  type: DetectedFieldType
  category: 'PERSONAL' | 'PROFESSIONAL' | 'EDUCATION' | 'APPLICATION' | 'SPECIAL'
  label: string
  autocompleteTokens: string[]
  aliases: string[]
  negativeAliases?: string[]
}

export const FIELD_TAXONOMY: FieldDefinition[] = [
  // ── PERSONAL ───────────────────────────────────────────────────────────────
  {
    type: 'fullName',
    category: 'PERSONAL',
    label: 'Full Name',
    autocompleteTokens: ['name'],
    aliases: [
      'full name',
      'fullname',
      'candidate name',
      'applicant name',
      'legal full name',
      'legal name',
      'your name',
      'complete name',
      'name (first and last)',
      'full legal name',
    ],
    negativeAliases: ['first name', 'last name', 'middle name', 'company name', 'school name'],
  },
  {
    type: 'firstName',
    category: 'PERSONAL',
    label: 'First Name',
    autocompleteTokens: ['given-name'],
    aliases: [
      'first name',
      'firstname',
      'given name',
      'candidate first name',
      'legal first name',
      'fname',
      'forename',
      'first_name',
      'first',
      'prenom',
    ],
    negativeAliases: ['last name', 'middle name'],
  },
  {
    type: 'middleName',
    category: 'PERSONAL',
    label: 'Middle Name',
    autocompleteTokens: ['additional-name'],
    aliases: [
      'middle name',
      'middlename',
      'middle initial',
      'mname',
      'middle_name',
      'middle',
    ],
    negativeAliases: ['first name', 'last name'],
  },
  {
    type: 'lastName',
    category: 'PERSONAL',
    label: 'Last Name',
    autocompleteTokens: ['family-name'],
    aliases: [
      'last name',
      'lastname',
      'family name',
      'surname',
      'candidate last name',
      'legal last name',
      'lname',
      'last_name',
      'last',
      'nom',
    ],
    negativeAliases: ['first name', 'middle name'],
  },
  {
    type: 'preferredName',
    category: 'PERSONAL',
    label: 'Preferred Name',
    autocompleteTokens: ['nickname'],
    aliases: [
      'preferred name',
      'preferred first name',
      'nickname',
      'chosen name',
      'known as',
      'goes by',
    ],
  },
  {
    type: 'email',
    category: 'PERSONAL',
    label: 'Email Address',
    autocompleteTokens: ['email'],
    aliases: [
      'email',
      'email address',
      'e-mail',
      'e-mail address',
      'candidate email',
      'personal email',
      'electronic mail',
      'mail',
    ],
    negativeAliases: ['confirm email', 'alternate email', 'referrer email'],
  },
  {
    type: 'phone',
    category: 'PERSONAL',
    label: 'Phone Number',
    autocompleteTokens: ['tel', 'tel-national', 'tel-local'],
    aliases: [
      'phone',
      'phone number',
      'mobile',
      'mobile number',
      'mobile phone',
      'contact number',
      'telephone',
      'cell phone',
      'cell',
      'tel',
      'primary phone',
    ],
    negativeAliases: ['extension', 'fax', 'emergency contact'],
  },
  {
    type: 'dateOfBirth',
    category: 'PERSONAL',
    label: 'Date of Birth',
    autocompleteTokens: ['bday', 'bday-day', 'bday-month', 'bday-year'],
    aliases: [
      'date of birth',
      'dob',
      'birth date',
      'birthday',
      'birthdate',
    ],
  },
  {
    type: 'gender',
    category: 'PERSONAL',
    label: 'Gender / Pronouns',
    autocompleteTokens: ['sex'],
    aliases: [
      'gender',
      'sex',
      'pronoun',
      'pronouns',
      'gender identity',
    ],
  },
  {
    type: 'address',
    category: 'PERSONAL',
    label: 'Street Address',
    autocompleteTokens: ['street-address', 'address-line1'],
    aliases: [
      'address',
      'street address',
      'address line 1',
      'address 1',
      'residential address',
      'home address',
      'street',
    ],
    negativeAliases: ['email address', 'ip address', 'web address'],
  },
  {
    type: 'city',
    category: 'PERSONAL',
    label: 'City',
    autocompleteTokens: ['address-level2'],
    aliases: [
      'city',
      'town',
      'municipality',
      'suburb',
    ],
  },
  {
    type: 'state',
    category: 'PERSONAL',
    label: 'State / Province',
    autocompleteTokens: ['address-level1'],
    aliases: [
      'state',
      'province',
      'region',
      'territory',
      'county',
    ],
    negativeAliases: ['statement', 'status'],
  },
  {
    type: 'country',
    category: 'PERSONAL',
    label: 'Country',
    autocompleteTokens: ['country-name', 'country'],
    aliases: [
      'country',
      'nation',
      'country of residence',
      'citizenship country',
      'current country',
    ],
    negativeAliases: ['authorized to work', 'work in this country', 'sponsorship', 'right to work'],
  },
  {
    type: 'postalCode',
    category: 'PERSONAL',
    label: 'Postal / Zip Code',
    autocompleteTokens: ['postal-code'],
    aliases: [
      'postal code',
      'postalcode',
      'zip code',
      'zipcode',
      'zip',
      'postcode',
      'pin code',
      'pincode',
    ],
  },

  // ── PROFESSIONAL ───────────────────────────────────────────────────────────
  {
    type: 'linkedinUrl',
    category: 'PROFESSIONAL',
    label: 'LinkedIn Profile',
    autocompleteTokens: ['url'],
    aliases: [
      'linkedin',
      'linkedin profile',
      'linkedin url',
      'linkedin link',
      'linkedin.com',
      'public profile',
    ],
  },
  {
    type: 'githubUrl',
    category: 'PROFESSIONAL',
    label: 'GitHub Profile',
    autocompleteTokens: ['url'],
    aliases: [
      'github',
      'github profile',
      'github url',
      'github link',
      'github.com',
      'git profile',
      'repository',
    ],
  },
  {
    type: 'portfolioUrl',
    category: 'PROFESSIONAL',
    label: 'Portfolio / Personal Site',
    autocompleteTokens: ['url'],
    aliases: [
      'portfolio',
      'portfolio url',
      'portfolio link',
      'portfolio website',
      'personal website',
      'online portfolio',
      'design portfolio',
      'work samples',
    ],
  },
  {
    type: 'websiteUrl',
    category: 'PROFESSIONAL',
    label: 'Website / Other Link',
    autocompleteTokens: ['url'],
    aliases: [
      'website',
      'website url',
      'personal site',
      'blog',
      'other website',
      'other link',
      'url',
    ],
  },
  {
    type: 'skills',
    category: 'PROFESSIONAL',
    label: 'Skills & Tech Stack',
    autocompleteTokens: [],
    aliases: [
      'skills',
      'core competencies',
      'technologies',
      'tech stack',
      'key skills',
      'skill set',
      'technical skills',
    ],
  },

  // ── EDUCATION ──────────────────────────────────────────────────────────────
  {
    type: 'institution',
    category: 'EDUCATION',
    label: 'University / Institution',
    autocompleteTokens: [],
    aliases: [
      'university',
      'college',
      'school',
      'institution',
      'educational institution',
      'academy',
      'alma mater',
    ],
  },
  {
    type: 'degree',
    category: 'EDUCATION',
    label: 'Degree',
    autocompleteTokens: [],
    aliases: [
      'degree',
      'qualification',
      'highest degree',
      'education level',
      'level of education',
      'degree earned',
    ],
  },
  {
    type: 'specialization',
    category: 'EDUCATION',
    label: 'Major / Field of Study',
    autocompleteTokens: [],
    aliases: [
      'major',
      'field of study',
      'specialization',
      'discipline',
      'area of study',
      'branch',
    ],
  },
  {
    type: 'graduationYear',
    category: 'EDUCATION',
    label: 'Graduation Year',
    autocompleteTokens: [],
    aliases: [
      'graduation year',
      'year of graduation',
      'grad year',
      'completion year',
      'end year',
      'passout year',
    ],
  },
  {
    type: 'cgpa',
    category: 'EDUCATION',
    label: 'GPA / CGPA',
    autocompleteTokens: [],
    aliases: [
      'gpa',
      'cgpa',
      'grade',
      'percentage',
      'marks',
      'academic score',
    ],
  },

  // ── APPLICATION ────────────────────────────────────────────────────────────
  {
    type: 'workAuthorization',
    category: 'APPLICATION',
    label: 'Work Authorization',
    autocompleteTokens: [],
    aliases: [
      'work authorization',
      'authorized to work',
      'legally authorized to work',
      'are you legally authorized to work',
      'eligible to work',
      'right to work',
      'work permit',
      'work eligibility',
    ],
  },
  {
    type: 'visaStatus',
    category: 'APPLICATION',
    label: 'Visa Sponsorship',
    autocompleteTokens: [],
    aliases: [
      'sponsorship',
      'visa sponsorship',
      'require sponsorship',
      'will you require sponsorship',
      'will you now or in the future require sponsorship',
      'need sponsorship',
      'visa status',
    ],
  },
  {
    type: 'expectedSalary',
    category: 'APPLICATION',
    label: 'Expected Salary',
    autocompleteTokens: [],
    aliases: [
      'expected salary',
      'desired salary',
      'salary expectation',
      'compensation expectation',
      'expected pay',
      'target compensation',
      'desired pay',
    ],
  },
  {
    type: 'noticePeriod',
    category: 'APPLICATION',
    label: 'Notice Period / Availability',
    autocompleteTokens: [],
    aliases: [
      'notice period',
      'availability',
      'how soon can you start',
      'earliest start date',
      'start date',
      'when can you start',
    ],
  },
  {
    type: 'currentCompany',
    category: 'APPLICATION',
    label: 'Current Employer',
    autocompleteTokens: ['organization'],
    aliases: [
      'current company',
      'current employer',
      'present company',
      'company',
      'organization',
      'employer',
    ],
  },
  {
    type: 'currentJobTitle',
    category: 'APPLICATION',
    label: 'Current Job Title',
    autocompleteTokens: ['organization-title'],
    aliases: [
      'current title',
      'current job title',
      'current role',
      'present role',
      'job title',
      'title',
    ],
  },
  {
    type: 'yearsOfExperience',
    category: 'APPLICATION',
    label: 'Years of Experience',
    autocompleteTokens: [],
    aliases: [
      'years of experience',
      'total experience',
      'overall experience',
      'relevant experience',
      'how many years of experience',
      'experience in years',
    ],
  },

  // ── SPECIAL ────────────────────────────────────────────────────────────────
  {
    type: 'resumeUpload',
    category: 'SPECIAL',
    label: 'Resume / CV File',
    autocompleteTokens: [],
    aliases: [
      'resume',
      'cv',
      'curriculum vitae',
      'upload resume',
      'attach resume',
      'upload cv',
      'attach cv',
      'resume file',
      'resume/cv',
    ],
  },
  {
    type: 'customQuestion',
    category: 'SPECIAL',
    label: 'Custom Application Question',
    autocompleteTokens: [],
    aliases: [
      'why do you want to work',
      'why are you interested',
      'describe your experience',
      'tell us about yourself',
      'why should we hire you',
      'cover letter',
      'additional information',
      'anything else',
      'what makes you a good fit',
      'personal statement',
    ],
  },
]
